/* MENU */
export const MENU_ITEMS = "MENU_ITEMS";
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const TOGGLE_CONTACT_US_MODAL = "TOGGLE_CONTACT_US_MODAL";
export const TOGGLE_PROFILE_MODAL = "TOGGLE_PROFILE_MODAL";
export const TOGGLE_CHANGE_PASSWORD_MODAL = "TOGGLE_CHANGE_PASSWORD_MODAL";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const REFRESH_USER = "REFRESH_USER";
export const REFRESH_USER_ERROR = "REFRESH_USER_ERROR";
export const REFRESH_USER_SUCCESS = "REFRESH_USER_SUCCESS";

export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CHANGE_PROFILE_ERROR = "CHANGE_PROFILE_ERROR";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

/* USER MANAGEMENT */
export const GET_USERS = "GET_USERS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const CHANGE_USER_AUTHORIZATION = "CHANGE_USER_AUTHORIZATION";
export const CHANGE_USER_AUTHORIZATION_ERROR =
  "CHANGE_USER_AUTHORIZATION_ERROR";
export const CHANGE_USER_AUTHORIZATION_SUCCESS =
  "CHANGE_USER_AUTHORIZATION_SUCCESS";

/* MEDIA */
export const GET_MEDIAS = "GET_MEDIAS";
export const GET_MEDIAS_ERROR = "GET_MEDIAS_ERROR";
export const GET_MEDIAS_SUCCESS = "GET_MEDIAS_SUCCESS";

/* LABORATORY TEST */
export const TOGGLE_SUBMIT_REQUEST_MODAL = "TOGGLE_SUBMIT_REQUEST_MODAL";
export const TOGGLE_EDIT_REQUEST_MODAL = "TOGGLE_EDIT_REQUEST_MODAL";
export const TOGGLE_RECEIVE_REQUEST_MODAL = "TOGGLE_RECEIVE_REQUEST_MODAL";
export const TOGGLE_APPROVE_REQUEST_MODAL = "TOGGLE_APPROVE_REQUEST_MODAL";
export const TOGGLE_DELETE_REQUEST_MODAL = "TOGGLE_DELETE_REQUEST_MODAL";
export const TOGGLE_SUBMIT_REPORT_MODAL = "TOGGLE_SUBMIT_REPORT_MODAL";
export const TOGGLE_EDIT_REPORT_MODAL = "TOGGLE_EDIT_REPORT_MODAL";
export const TOGGLE_APPROVE_REPORT_MODAL = "TOGGLE_APPROVE_REPORT_MODAL";
export const TOGGLE_REVISE_REPORT_MODAL = "TOGGLE_REVISE_REPORT_MODAL";
export const TOGGLE_DOWNLOAD_DOCUMENT_MODAL = "TOGGLE_DOWNLOAD_DOCUMENT_MODAL";
export const TOGGLE_REPORT_HISTORY_MODAL = "TOGGLE_REPORT_HISTORY_MODAL";

export const GET_LABORATORY_TESTS = "GET_LABORATORY_TESTS";
export const GET_LABORATORY_TESTS_ERROR = "GET_LABORATORY_TESTS_ERROR";
export const GET_LABORATORY_TESTS_SUCCESS = "GET_LABORATORY_TESTS_SUCCESS";

export const CHANGE_SELECTED_LABORATORY_TEST_YEAR =
  "CHANGE_SELECTED_LABORATORY_TEST_YEAR";

export const SUBMIT_LABORATORY_TEST_REQUEST = "SUBMIT_LABORATORY_TEST_REQUEST";
export const SUBMIT_LABORATORY_TEST_REQUEST_ERROR =
  "SUBMIT_LABORATORY_TEST_REQUEST_ERROR";
export const SUBMIT_LABORATORY_TEST_REQUEST_SUCCESS =
  "SUBMIT_LABORATORY_TEST_REQUEST_SUCCESS";

export const EDIT_LABORATORY_TEST_REQUEST = "EDIT_LABORATORY_TEST_REQUEST";
export const EDIT_LABORATORY_TEST_REQUEST_ERROR =
  "EDIT_LABORATORY_TEST_REQUEST_ERROR";
export const EDIT_LABORATORY_TEST_REQUEST_SUCCESS =
  "EDIT_LABORATORY_TEST_REQUEST_SUCCESS";

export const APPROVE_LABORATORY_TEST_REQUEST =
  "APPROVE_LABORATORY_TEST_REQUEST";
export const APPROVE_LABORATORY_TEST_REQUEST_ERROR =
  "APPROVE_LABORATORY_TEST_REQUEST_ERROR";
export const APPROVE_LABORATORY_TEST_REQUEST_SUCCESS =
  "APPROVE_LABORATORY_TEST_REQUEST_SUCCESS";

export const DELETE_LABORATORY_TEST_REQUEST = "DELETE_LABORATORY_TEST_REQUEST";
export const DELETE_LABORATORY_TEST_REQUEST_ERROR =
  "DELETE_LABORATORY_TEST_REQUEST_ERROR";
export const DELETE_LABORATORY_TEST_REQUEST_SUCCESS =
  "DELETE_LABORATORY_TEST_REQUEST_SUCCESS";

export const RECEIVE_LABORATORY_TEST_REQUEST =
  "RECEIVE_LABORATORY_TEST_REQUEST";
export const RECEIVE_LABORATORY_TEST_REQUEST_ERROR =
  "RECEIVE_LABORATORY_TEST_REQUEST_ERROR";
export const RECEIVE_LABORATORY_TEST_REQUEST_SUCCESS =
  "RECEIVE_LABORATORY_TEST_REQUEST_SUCCESS";

export const SUBMIT_LABORATORY_TEST_REPORT = "SUBMIT_LABORATORY_TEST_REPORT";
export const SUBMIT_LABORATORY_TEST_REPORT_ERROR =
  "SUBMIT_LABORATORY_TEST_REPORT_ERROR";
export const SUBMIT_LABORATORY_TEST_REPORT_SUCCESS =
  "SUBMIT_LABORATORY_TEST_REPORT_SUCCESS";

export const EDIT_LABORATORY_TEST_REPORT = "EDIT_LABORATORY_TEST_REPORT";
export const EDIT_LABORATORY_TEST_REPORT_ERROR =
  "EDIT_LABORATORY_TEST_REPORT_ERROR";
export const EDIT_LABORATORY_TEST_REPORT_SUCCESS =
  "EDIT_LABORATORY_TEST_REPORT_SUCCESS";

export const APPROVE_LABORATORY_TEST_REPORT = "APPROVE_LABORATORY_TEST_REPORT";
export const APPROVE_LABORATORY_TEST_REPORT_ERROR =
  "APPROVE_LABORATORY_TEST_REPORT_ERROR";
export const APPROVE_LABORATORY_TEST_REPORT_SUCCESS =
  "APPROVE_LABORATORY_TEST_REPORT_SUCCESS";

export const REVISE_LABORATORY_TEST_REPORT = "REVISE_LABORATORY_TEST_REPORT";
export const REVISE_LABORATORY_TEST_REPORT_ERROR =
  "REVISE_LABORATORY_TEST_REPORT_ERROR";
export const REVISE_LABORATORY_TEST_REPORT_SUCCESS =
  "REVISE_LABORATORY_TEST_REPORT_SUCCESS";

export const DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT =
  "DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT";
export const DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT_ERROR =
  "DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT_ERROR";
export const DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT_SUCCESS =
  "DOWNLOAD_LABORATORY_TEST_REQUEST_DOCUMENT_SUCCESS";

export const DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT =
  "DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT";
export const DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT_ERROR =
  "DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT_ERROR";
export const DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT_SUCCESS =
  "DOWNLOAD_LABORATORY_TEST_REPORT_DOCUMENT_SUCCESS";

export const DOWNLOAD_LABORATORY_TEST_ATTACHMENT =
  "DOWNLOAD_LABORATORY_TEST_ATTACHMENT";
export const DOWNLOAD_LABORATORY_TEST_ATTACHMENT_ERROR =
  "DOWNLOAD_LABORATORY_TEST_ATTACHMENT_ERROR";
export const DOWNLOAD_LABORATORY_TEST_ATTACHMENT_SUCCESS =
  "DOWNLOAD_LABORATORY_TEST_ATTACHMENT_SUCCESS";

/* Chemical Solution Control */
export const TOGGLE_CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG =
  "TOGGLE_CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG";
export const TOGGLE_EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG =
  "TOGGLE_EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG";
export const TOGGLE_DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG =
  "TOGGLE_DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG";
export const TOGGLE_REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG =
  "TOGGLE_REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_DIALOG";
export const TOGGLE_CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";
export const TOGGLE_EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";
export const TOGGLE_DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";
export const TOGGLE_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";
export const TOGGLE_UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";
export const TOGGLE_ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG =
  "TOGGLE_ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_DIALOG";

export const CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_STATUS =
  "CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_STATUS";
export const CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_WORKSHEET =
  "CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_WORKSHEET";
export const CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "CHANGE_SELECTED_CHEMICAL_SOLUTION_CONTROL_RECORD";

export const GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS =
  "GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS";
export const GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS_ERROR =
  "GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS_ERROR";
export const GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS_SUCCESS =
  "GET_CHEMICAL_SOLUTION_CONTROL_WORKSHEETS_SUCCESS";

export const CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET";
export const CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR";
export const CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS";

export const EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET";
export const EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR";
export const EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS";

export const DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET";
export const DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR";
export const DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS";

export const REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET =
  "REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET";
export const REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR =
  "REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_ERROR";
export const REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS =
  "REVISE_CHEMICAL_SOLUTION_CONTROL_WORKSHEET_SUCCESS";

export const CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "CREATE_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export const EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "EDIT_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export const DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "DELETE_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export const VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export const UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "UNDO_VERIFY_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export const ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD =
  "ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD";
export const ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR =
  "ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_ERROR";
export const ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS =
  "ATTACH_CCR_CHEMICAL_SOLUTION_CONTROL_RECORD_SUCCESS";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./userManagement/actions";
export * from "./media/actions";
export * from "./qaLaboratoryTest/actions";
export * from "./qaChemicalSolutionControl/actions";
